<h1>Victoria Lovatt Morris</h1>
<img src="images/teachers/bio-pages/victoria-lovatt-morris.jpg" alt="Victoria Lovatt Morris" class="w350fr">
<p>Victoria came to yoga at The Space as a new (exhausted) mum and newcomer to Thame five years ago. After enjoying pre-natal yoga in London, when she moved to Thame with her new baby starting classes at The Space gave her a sense of her own space…the glorious freedom of taking a whole 90 minutes to take care of her body and mind, to nourish with movement, breathwork and meditation. The opportunity to use her time in class to pay real attention to her body, to allow emotions to be felt and processed, created a way in which to embrace vulnerability while building strength in body and mind. The opportunity to accept however you feel that day, allow it, embrace it…it provided an essential self-care toolkit for a busy and demanding daily life of full time work and full time mother, daughter, wife, friend, colleague.</p>

 <p>The curious alchemy of yoga was a profoundly healing and empowering experience that transformed life on and off the mat, the path has lead Victoria on retreats around the world. From juice retreats in Turkish mountains to an inversion immersion in the Lake District (she still can’t hold that handstand). The community is something that Victoria has taken great solace in, and it has guided her path to become a teacher through being inspired by the gentle support and guidance she received, every training has led intuitively on from personal recommendations, until she ultimately completed 300 hours of  yoga teacher training with <a href="http://www.appleyoga.com/">appleyoga</a>. A distillation of years of study and a lifetime of movement practice, Katy Appleton’s appleyoga approach to vinyasa flow is an intelligent and transformational methodology that is easy to learn and helps people to go into their practice with lightness and grace. It is biomechanically savvy, features key actions for empowerment and freedom in the body, and is grounded in principles of sequencing that allow people to soar in every class. Learning intuitive creative sequencing that is body led was deeply appealing, but even more so the invitation to consider the inner wisdom of the heart space, to learn how to apply both effort and ease, and to appreciate the importance of softening. To meet yourself exactly where you are on that day, at that time.</p>

 

<p>Victoria's training continues as she explores her healers path with yogabodywork and forrest yoga with <a href="https://www.jambodragon.com/">Jambo Dragon</a>, and with <a href="https://stralayoga.com/">Strala's</a>  combination of the movement and healing systems of East Asian traditions with yoga.</p>
